---
- name: set distro-specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - default.yml

- name: install dependencies
  package: name={{ item }}
  with_items:
    - '{{ prerequisites }}'

- name: check if carbon-c-relay is already installed
  command: /usr/local/bin/ccrelay -v
  register: ccrelay_installed
  failed_when: no
  changed_when: ccrelay_installed.rc != 0

- name: download carbon-c-relay tarball
  get_url: url=https://github.com/grobian/carbon-c-relay/archive/v{{ ccrelay_version }}.tar.gz dest=/tmp/carbon-c-relay-{{ ccrelay_version }}.tar.gz
  when:
    - ccrelay_installed.rc != 0

- name: unarchive tarball
  command: tar xzvf /tmp/carbon-c-relay-{{ ccrelay_version }}.tar.gz -C /tmp/
  when:
    - ccrelay_installed.rc != 0

- name: build carbon-c-relay
  make:
    chdir: /tmp/carbon-c-relay-{{ ccrelay_version }}
  when:
    - ccrelay_installed.rc != 0
  register: ccrelay_build

- name: move binary to destination directory
  command: mv /tmp/carbon-c-relay-{{ ccrelay_version }}/relay {{ binary_destination }}/ccrelay
  when: ccrelay_build.changed
  
- name: drop configs
  template: dest={{ binary_destination }}/{{ item }} src={{ item }}.j2
  with_items:
    - ccrelay.conf
  notify:
    - reload systemd
    - restart carbon-c-relay

- name: drop systemd unit file
  template: src=ccrelay.service.j2 dest=/etc/systemd/system/ccrelay.service
  notify:
    - reload systemd
    - restart carbon-c-relay
  when:
    - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")
    - "{{ ansible_distribution_version|int }} == 7"

- name: drop sysv init script
  template: src={{ item }}.j2 dest=/{{ item }} mode=0755
  notify:
    - restart carbon-c-relay
  when:
    - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")
    - "{{ ansible_distribution_version|int }} == 6"
  with_items:
    - etc/init.d/ccrelay

- name: remove source
  file: path=/tmp/carbon-c-relay-{{ ccrelay_version }}.tar.gz state=absent
  with_items:
    - /tmp/carbon-c-relay-{{ ccrelay_version }}.tar.gz
    - /tmp/carbon-c-relay-{{ ccrelay_version }}
  when: ccrelay_build.changed

- name: ensure log dir exists
  file: path=/var/log/ccrelay/ state=directory owner=root group=root mode=0744
  when:
    - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")
    - "{{ ansible_distribution_version|int }} == 6"
